// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: mcp.proto

package pdfprocessor

import (
	"context"

	"ai-gozero-agent/mcp/types/mcp"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Metadata    = mcp.Metadata
	PdfRequest  = mcp.PdfRequest
	PdfResponse = mcp.PdfResponse

	PdfProcessor interface {
		// 流式上传PDF并返回解析文本
		ExtractText(ctx context.Context, opts ...grpc.CallOption) (mcp.PdfProcessor_ExtractTextClient, error)
	}

	defaultPdfProcessor struct {
		cli zrpc.Client
	}
)

func NewPdfProcessor(cli zrpc.Client) PdfProcessor {
	return &defaultPdfProcessor{
		cli: cli,
	}
}

// 流式上传PDF并返回解析文本
func (m *defaultPdfProcessor) ExtractText(ctx context.Context, opts ...grpc.CallOption) (mcp.PdfProcessor_ExtractTextClient, error) {
	client := mcp.NewPdfProcessorClient(m.cli.Conn())
	return client.ExtractText(ctx, opts...)
}
