// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type ChatResponse struct {
	Content string `json:"content"`
	IsLast  bool   `json:"isLast"`
}

type InterViewAPPChatReq struct {
	Message string `form:"message"`
	ChatId  string `form:"chatId"`
}
