// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"ai-gozero-agent/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// SSE流式接口
				Method:  http.MethodGet,
				Path:    "/interview_app/chat/sse",
				Handler: ChatHandler(serverCtx),
			},
		},
	)
}
