// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: mcp.proto

package server

import (
	"ai-gozero-agent/mcp/internal/logic"
	"ai-gozero-agent/mcp/internal/svc"
	"ai-gozero-agent/mcp/types/mcp"
)

type PdfProcessorServer struct {
	svcCtx *svc.ServiceContext
	mcp.UnimplementedPdfProcessorServer
}

func NewPdfProcessorServer(svcCtx *svc.ServiceContext) *PdfProcessorServer {
	return &PdfProcessorServer{
		svcCtx: svcCtx,
	}
}

// 流式上传PDF并返回解析文本
func (s *PdfProcessorServer) ExtractText(stream mcp.PdfProcessor_ExtractTextServer) error {
	l := logic.NewExtractTextLogic(stream.Context(), s.svcCtx)
	return l.ExtractText(stream)
}
